// <auto-generated />
using System;
using InteleqtCapture.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace InteleqtCapture.Data.Migrations
{
    [DbContext(typeof(CustomerContext))]
    [Migration("20190326091051_DateMigration")]
    partial class DateMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("InteleqtCapture.Models.Annuity", b =>
                {
                    b.Property<string>("EntityId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTimeOffset>("AnniversaryDate");

                    b.Property<double>("AnnuityAmount");

                    b.Property<string>("EntityFullName");

                    b.Property<DateTimeOffset>("RenewalDate");

                    b.Property<DateTimeOffset>("StartDate");

                    b.HasKey("EntityId");

                    b.ToTable("annuities");
                });

            modelBuilder.Entity("InteleqtCapture.Models.Maintenance", b =>
                {
                    b.Property<string>("EntityId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("EntityFullName");

                    b.Property<string>("Item");

                    b.Property<string>("Product");

                    b.Property<string>("ProductCategory");

                    b.Property<int>("Quantity");

                    b.Property<DateTimeOffset>("RenewalDate");

                    b.Property<DateTimeOffset>("StartDate");

                    b.Property<double>("UnitPrice");

                    b.Property<int>("Value");

                    b.Property<int>("YearlyMaintenance");

                    b.HasKey("EntityId");

                    b.ToTable("maintenances");
                });
#pragma warning restore 612, 618
        }
    }
}
